## --- Project-wide settings
project:
  type: book
  output-dir: docs

metadata-files:
  - inst/assets/_book.yml
  - inst/assets/_website.yml

## --- Format options
format: 
  html:
    grid:
      sidebar-width: 500px
      body-width: 1100px
    theme: 
      - cosmo
      - inst/assets/book.scss
    highlight-style: atom-one
    code-link: true
    editor: visual
    citation-location: margin
    bibliography: inst/assets/bibliography.bib
    from: markdown+emoji

## --- knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "## " 
    cache: false
    fig.align: "center"
    python.reticulate: false
